### ISSUE TITLE
Récupération de ces propres stats

### ISSUE THREAD

**Issue by myki57** [ttwthomas/warzon2elasticsearch#4]
Salut,
j'ai réussi à faire tourner grafana et elastic, puis j'ai variabiliser les players pour afficher plusieurs stats sur le même graphe. Jusque là tout va bien. 

Par contre, quand je passe le script python, je vois qu'il ne trouve que mes potes. Enfin je veux dire que dans le retour cli il n'affiche que mes potes. Ce qui se vérifie dans Grafana puisque moi je n'apparait pas. 

Du coup en regardant le code j'ai l'impression que ton script ne passe que dans la méthode Lamba_handler via :
asyncio.get_event_loop().run_until_complete(lambda_handler())

Et pas du tout dans la fonction get_player_stat(). 

Je me trompe peut etre, suis pas un expert python. J'ai essayé de lancer la fonction get player stat dans lambda handler sans succès.

**Comment by ttwthomas** [comment]
oui la fonction  get_player_stat n'est jamais appelée, je l'utilisais pour
chercher le nom d'un joueur juste avec son pseudo.
pour avoir mes stats je rajoutais mon pseudo a l'initialisation de la
variable   friends_usernames
idealement il faudrait rajouter client.me.profile() (ou quelque chose comme
ca) a l'array pour que ça soit automatique.

**Comment by myki57** [comment]
OK merci pour l'info. 

J'ai une autre question au passage, comment est fait le rafraichissement des data ? C'est à chaque fois qu'on passe la commande python j'imagine. Du coup tu l'as automatisée comment ? 

Merci d'avance.

**Comment by ttwthomas** [comment]
C'est pas automatisé :)
Dans la video tu me vois faire un boucle en bash qui lance le script toutes
les 5min :)
Ca ressemble a ca:
while true; do docker exec pythonwz warzone.py ; sleep 600; done

**Comment by myki57** [comment]
Ok merci pour le retour j'avais zappé cette partie là. 

Par contre dernière question (promis), j'ajoute une référence à mon pseudo comme sur la vidéo dans l'init du tableau friends_username (soit directement {"username" etc.. ou soit via friends_username.append juste après l'init du tab) mais cela ne fonctionne pas. J'ai un message d'erreur comme si la connexion ne s'établissait pas : 
`[/share/Containers/CallOfDuty] # docker exec pythonwz python warzone.py
saving Myki#4854656
Traceback (most recent call last):
  File "/code/warzone.py", line 53, in <module>
    asyncio.get_event_loop().run_until_complete(lambda_handler())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/code/warzone.py", line 14, in lambda_handler
    await save_player_stats(client, player)
  File "/code/warzone.py", line 31, in save_player_stats
    matches = await client.GetPlayerMatchesSummary(
  File "/usr/local/lib/python3.9/site-packages/callofduty/client.py", line 764, in GetPlayerMatchesSummary
    await self.http.GetPlayerMatchesDetailed(
  File "/usr/local/lib/python3.9/site-packages/callofduty/http.py", line 253, in GetPlayerMatchesDetailed
    return await self.Send(
  File "/usr/local/lib/python3.9/site-packages/callofduty/http.py", line 113, in Send
    raise HTTPException(res.status_code, data)
callofduty.errors.HTTPException: HTTP 200 - Not permitted: user not found`

J'imagine qu'il trouve pas mon pseudo puisque le code plante après la phase "saving", mais c'est bizarre car je suis sûr du pseudo.

Difficile de troubleshooter dans une container, mais merci d'avance pour ton aide.

**Comment by ttwthomas** [comment]
C'est exactement le problème que je décris dans la video haha.
En punition tu dois la re-regarder et mettre un like.
Si tu trouves toujours pas jte dirai comment débloquer ;)

**Comment by myki57** [comment]
Ouais c'est le prob de SSO. Mais j'ai déjà fait la manip de changer mon code. 

En fait si j'enlève la partie Init de tableau avec mon login, le script fonctionne. Si j'ajoute l'init avec mon username j'ai le retour précédent. 

Ce qui est bizarre.

**Comment by ttwthomas** [comment]
Tu dois mettre 
`    friends_usernames = [{"username":"tonusername#123", "platform":"Activision"}]`
(si ton compte est activision)

**Comment by AverellBerlin** [comment]
Je pige pas non plus, j'ai la meme "erreur" 200. Pourtant si je vais sur activision.com je peux me logger sans passer par battlenet (j'ai fait la manip de changement de pseudo). 

Traceback (most recent call last):
  File "/code/warzone.py", line 52, in <module>
    asyncio.get_event_loop().run_until_complete(lambda_handler())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/code/warzone.py", line 10, in lambda_handler
    friends = await get_friends(client)
  File "/code/warzone.py", line 45, in get_friends
    friends = await client.GetMyFriends()
  File "/usr/local/lib/python3.9/site-packages/callofduty/client.py", line 366, in GetMyFriends
    data: dict = (await self.http.GetMyFriends())["data"]
  File "/usr/local/lib/python3.9/site-packages/callofduty/http.py", line 199, in GetMyFriends
    return await self.Send(
  File "/usr/local/lib/python3.9/site-packages/callofduty/http.py", line 113, in Send
    raise HTTPException(res.status_code, data)
callofduty.errors.HTTPException: HTTP 200 - Not permitted: not authenticated

**Comment by AverellBerlin** [comment]
en gros mon warzone.py ressemble a ca:

import asyncio, json , os
from callofduty import Mode, Platform, Title, Login
from elasticsearch import Elasticsearch
from datetime import datetime

async def lambda_handler():
    login = os.environ.get('monemailactivion')
    password = os.environ.get('lemotdepasse')
    client = await Login(login, password)
    friends = await get_friends(client)
    for player in friends:
        username=player['username']
        print(f"saving {username}")
        await save_player_stats(client, player)

async def get_player_stats():
    login = os.environ.get('monemailactivion')
    password = os.environ.get('lemotdepasse')
    client = await Login(login, password)
    playername="BrokyBrawks"
    results = await client.SearchPlayers(
        Platform.Activision, playername, limit=30)
    print(results)
    for player in results:
        profile = await player.profile(Title.ModernWarfare, Mode.Multiplayer)
        if profile["lifetime"]["all"]["properties"] is not None :
            print(f"{player.username} ({player.platform.name})")  
            # print(profile["lifetime"]["all"]["properties"]["kdRatio"])

async def save_player_stats(client, player):
    matches = await client.GetPlayerMatchesSummary(
        player["platform"] , player["username"],Title.ModernWarfare , Mode.Warzone, limit=20)
    body = {
        'name': player["username"], 
        'stats': matches,
        'timestamp': datetime.now()
    }
    es = Elasticsearch("es01")
    es.indices.create(index='wz', ignore=400)
    res = es.index(index="wz", body=body)
    print(res)


async def get_friends(client):
    friends = await client.GetMyFriends()
    friends_usernames = [{"username":"AverellB#5448840", "platform":"Activision"}]
    for friend in friends:
        if "#" in friend.username:
            friends_usernames.append({"username":friend.username, "platform":friend.platform})
    return friends_usernames

asyncio.get_event_loop().run_until_complete(lambda_handler())


J'ai pas activé la double authentication sur activision quand cela m'a été demandé btw.

**Comment by ttwthomas** [comment]
Essayes avec
"platform":Platform.BattleNet
 ?

**Comment by ttwthomas** [comment]
ah oui et peut etre que `  "platform":"Activision"  ` marche pas mais
 `"platform":  Platform.Activision` marche ?

**Comment by myki57** [comment]
Hello, 
pour moi en passant par  "platform":Platform.Activision}) 

Ca marche niquel. 

Merci pour l'aide.

**Comment by ttwthomas** [comment]
all good
